# Generated by Django 5.2.3 on 2025-06-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
