# Generated by Django 5.2.3 on 2025-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
