# Generated by Django 5.2.3 on 2025-06-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_viewinghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewinghistory',
            name='video_title',
        ),
        migrations.AddField(
            model_name='viewinghistory',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.video'),
        ),
    ]
